djangoProject4/urls.py
from django.contrib import admin
from django.urls import include, path


app_name='photoalbum'
urlpatterns = [
    path('photoalbum/', include('photoalbum.urls')),
    path('admin/', admin.site.urls),
]

photoalbum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views
from . import models

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name='photoalbum'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('upload', views.upload_file, name='upload'),
]
urlpatterns += staticfiles_urlpatterns()

photoalbum/models.py
import datetime

from django.db import models
from django.utils import timezone

class Image(models.Model):
    image_name = models.FileField(upload_to='photoalbum/static/photoalbum/image/')
    filename=models.CharField( max_length=500)
    date_published = models.DateTimeField('date published')
    def __str__(self):
            return self.image_name ;

    def was_published_recently(self):
        return self.date_published >= timezone.now() - datetime.timedelta(days=1)
# Create your models here.

photoalbum/forms.py
from django import forms

class UploadFileForm(forms.Form):
    file = forms.FileField()

photoalbum/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from .models import Image
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .functions import handle_uploaded_file
from django.utils import timezone
from .forms import UploadFileForm


# Create your views here.
class IndexView(generic.ListView):
    template_name = 'photoalbum/index.html'
    context_object_name = 'latest_image_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Image.objects.order_by('-date_published')[:5]

class DetailView(generic.DetailView):
    model = Image
    template_name = 'photoalbum/detail.html'



def upload_file(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            instance = Image(image_name=request.FILES['file'],filename= request.FILES['file'].name ,date_published=timezone.now())
            instance.save()
            return HttpResponseRedirect('/photoalbum/')
    else:
        form = UploadFileForm()
    return render(request, 'photoalbum/upload.html', {'form': form})

photoalbum/templates/photoalbum/detail.html
<h1>{{ image.image_name }}</h1>
<h2>Uploaded at: {{ image.date_publishedgi }}</h2>
<ul>
    {% load static %}
                <img src=" {% static  'photoalbum/image/'%}{{ image.filename }}">
</ul>

photoalbum/templates/photoalbum/index.html
{% if latest_image_list %}
    <ul>
    {% for image in latest_image_list %}
        <li><a href="{% url 'photoalbum:detail' image.id%}">
            {% load static %}
                <img src=" {% static  'photoalbum/image/'%}{{ image.filename }}">
        </a>
        </li>
    {% endfor %}
    <li><a href="{% url 'photoalbum:upload'  %}">Upload Image</a></li>
    </ul>
{% else %}
    <p>No image are available.</p>
{% endif %}

photoalbum/templates/photoalbum/upload.html
<form method="post" enctype=multipart/form-data>
    {% csrf_token %}
{{ form }}
<input type="submit" value="Send">
</form>